function prefac = pn2chirp_prefac_etam2tau1(fMin, geomFac)
%Prefactors in the conversion of eta, M to tau1
%P = PN2CHIRP_PREFAC_ETAM2TAU1(Fmin,G)
%Generates the prefactors in the conversion from symmetric mass ratio
%(eta), and total mass (M) to chirp time tau1 for a restricted 2PN
%waveform. G is the constant G*pi*Fmin/c^3 generated by PN2CHIRP_GEOMFAC. P
%has 4 elements that contain values of the prefactors in the order (left to
%right) they appear in the expressions given in OverLeaf: "BINARIES User
%Manual / MathNotes_LAL.tex".

%Soumya D. Mohanty, Apr 2023

fMinInv = 1/fMin;

%Use meaningful names for the prefactors
cht1pre= (5/(192*pi))*fMinInv;
cht1f0 = geomFac^(-1);
cht1f1 = 743/336;
cht1f2 = 11/4;

%Assign prefactors to output array
prefac(1) = cht1pre;
prefac(2) = cht1f0;
prefac(3) = cht1f1;
prefac(4) = cht1f2;
                      