function prefac = pn2chirp_prefac_etam2tau2(fMin, geomFac)
%Prefactors in the conversion of eta, mu, M to tau2
%P = PN2CHIRP_PREFAC_ETAM2TAU1P5(Fmin,G)
%Generates the prefactors in the conversion from symmetric mass ratio
%(eta), and total mass (M) to chirp time tau2 for a restricted 2PN
%waveform. G is the constant G*pi*Fmin/c^3 generated by PN2CHIRP_GEOMFAC. P
%has 5 elements that contain values of the prefactors in the order (left to
%right) they appear in the expressions given in OverLeaf: "BINARIES User
%Manual / MathNotes_LAL.tex".

%Soumya D. Mohanty, Apr 2023

fMinInv = 1/fMin;

%Use meaningful names for the prefactors
cht2pre=(5/(128*pi))*fMinInv;
cht2f0 = geomFac^(-1/3);
cht2f1 = 3058673/1016064;
cht2f2 = 5429/1008;
cht2f3 = 617/144;

%Assign prefactors to output array
prefac(1) = cht2pre;
prefac(2) = cht2f0;
prefac(3) = cht2f1;
prefac(4) = cht2f2;
prefac(5) = cht2f3;